# Матрицы, векторы

In [2]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
%config InlineBackend.figure_format = 'svg'

### Задание 1. 
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.  
Вычислите, по возможности не используя программирование: $(5E)^{-1}$, где Е – единичная матрица размера 5х5.


In [3]:
a = (np.matrix([[ 1, 3],[ -1, 1],[2, 5]]))
b = np.array([[ 2, -6,  1],[ 1, 3, -1]])
c = np.array([[ -1],[ 2],[4]])
print("А = ", a)
print("B = ", b)
print("C = ", c)
print(a.shape, b.shape, c.shape)

А =  [[ 1  3]
 [-1  1]
 [ 2  5]]
B =  [[ 2 -6  1]
 [ 1  3 -1]]
C =  [[-1]
 [ 2]
 [ 4]]
(3, 2) (2, 3) (3, 1)


По правилу умножения матриц существует произведения ${A\cdot{B}=D_{3x3}}$, ${B\cdot{A}=F_{2x2}}$,${B\cdot{C}=G_{2x1}}$, а значит можно найти и произведение ${D\cdot{C}=H_{3x1}}$


In [4]:
d = np.dot(a, b)
print(d)
print(d.shape)

[[ 5  3 -2]
 [-1  9 -2]
 [ 9  3 -3]]
(3, 3)


In [5]:
f = np.dot(b,a)
print(f)
print(f.shape)

[[10  5]
 [-4  1]]
(2, 2)


In [6]:
g = np.dot(b,c)
print(g)
print(g.shape)

[[-10]
 [  1]]
(2, 1)


In [7]:
h = np.dot(d,c)
print(h)
print(h.shape)

[[ -7]
 [ 11]
 [-15]]
(3, 1)


In [8]:
E = np.identity(5)
#print(5*e)
w=np.linalg.inv(5*E)
print(w)

[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


### Задание 2. 
Вычислите определитель: $\begin{vmatrix}1&2&3\\4&0&6\\7&8&9\end{vmatrix}$

Вычислим, используя теорему о разложении

 $\det A=\begin{vmatrix}1&2&3\\4&0&6\\7&8&9\end{vmatrix}=-4{\cdot{\begin{vmatrix}2&3\\8&9\end{vmatrix}}} + 0 -6{\cdot{\begin{vmatrix}1&2\\7&8\end{vmatrix}}} = -4{\cdot{(18-24)}}-6{\cdot{(8-14)}}=24+36=60$.

In [11]:
# в программе
A = np.array([[ 1, 2,  3],[ 4, 0, 6], [ 7, 8, 9]])
print("det(A)=", np.linalg.det(A))

det(A)= 59.999999999999986


### Задание 3. 
1. Вычислите матрицу, обратную данной: 

$ A=\begin{pmatrix}1&2&3\\4&0&6\\7&8&9\end{pmatrix}$

In [12]:
A = np.array([[ 1, 2, 3],[ 4, 0, 6], [ 7, 8, 9]])
print(np.linalg.inv(A))

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


2. Приведите пример матрицы 4х4, ранг которой равен 1. 
  
Если все миноры второго порядка равны нулю, то ранг равен единице.


In [13]:
B = np.array([[ 1, 2, 0, 5],[ 2, 4, 0, 10], [4, 8, 0, 20], [ 5, 10, 0, 25]])

print("matrix_rank B =", np.linalg.matrix_rank(B, 0.001))

matrix_rank B = 1


### Задание 4.  
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)


In [50]:
a = np.array([ 1,5])
b = np.array([ 2, 8])
np.dot(a, b)

42

Проверка: ${\overline{a}\cdot{\overline{b}}=1\cdot2+5\cdot8=42}$

### Задание 5.  

Вычислите смешанное произведение трех векторов: (1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 

In [51]:
a = np.array([ 1, 5, 0])
b = np.array([ 2, 8, 7])
c = np.array([ 7, 1.5, 3])

v = np.cross(a, b)
print(np.inner(v, c))

228.5


Проверка: 
смешанное произведение векторов можно найти как определитель матрицы, составленных из координат этих векторов

${\overline{a}\cdot{\overline{b}}\cdot{\overline{c}}}=\begin{vmatrix}1&5&0\\2&8&7\\7&1.5&3\end{vmatrix}$

In [39]:
abc = np.array([[ 1, 5, 0],[ 2, 8, 7], [ 7, 1.5, 3]])
print(np.linalg.det(abc))

228.50000000000009
